language: elm

node_js: node

elm:
  - latest-0.19.1
elm_test: 0.19.1
elm_format: 0.8.2

script: make all
deploy:
  provider: pages
  local-dir: out/
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
